### ISSUE TITLE
Getting these 2 errors in WOTLK Beta. 

### ISSUE THREAD

**Issue by NoobTaco** [TheKrowi/Krowi_AchievementFilter#19]
The addon is also not showing on the UI and seems to be blocked.

**First error on load.**
```
1x Krowi_AchievementFilter\GUI\GUI.lua:301: attempt to compare nil with number
[string "@Krowi_AchievementFilter\GUI\GUI.lua"]:301: in function <Krowi_AchievementFilter\GUI\GUI.lua:300>
[string "=[C]"]: in function `sort'
[string "@Krowi_AchievementFilter\GUI\GUI.lua"]:300: in function `TabsOrderGetActiveKeys'
[string "@Krowi_AchievementFilter\Globals.lua"]:448: in function `ChangeAchievementMicroButtonOnClick'
[string "@Krowi_AchievementFilter\Krowi_AchievementFilter-39.1.lua"]:84: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:35>

Locals:
a = <table> {
 1 = "Blizzard_AchievementUI"
 2 = "Guild"
}
b = <table> {
 1 = "Krowi_AchievementFilter"
 2 = "Achievements"
 3 = 3
}
(*temporary) = nil
(*temporary) = 3
(*temporary) = "attempt to compare nil with number"
```

**Second bug after a moment of initial UI loading.** Also happens when opening the achievement UI
```
1x ...ceKrowi_AchievementFilter\Data\EventData.lua:118: attempt to index global 'EventDetails' (a nil value)
[string "@Krowi_AchievementFilter\Data\EventData.lua"]:118: in function `getActiveEvents'
[string "@Krowi_AchievementFilter\GUI\Misc\AlertSystem.lua"]:33: in function <...Ons\Krowi_AchievementFilter\GUI\Misc\AlertSystem.lua:28>
[string "@Krowi_AchievementFilter\GUI\Misc\AlertSystem.lua"]:49: in function `ShowActiveWorldEvents'
[string "@Krowi_AchievementFilter\Krowi_AchievementFilter-39.1.lua"]:94: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:92>

Locals:
activeWorldEvents = <table> {
}
(*temporary) = nil
(*temporary) = false
(*temporary) = false
(*temporary) = "attempt to index global 'EventDetails' (a nil value)"
diagnostics = <table> {
 TraceEnabled = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:36
 Debug = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:9
 DebugEnabled = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:33
 Trace = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:26
 Load = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:32
 DebugTable = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:15
}
GetSavedWorldEvents = <function> defined @Krowi_AchievementFilter\Data\EventData.lua:128
GetNewWorldEvents = <function> defined @Krowi_AchievementFilter\Data\EventData.lua:146
```

**Comment by TheKrowi** [comment]
Not much time the coming days to look at it unfortunately but will have a look from the moment I have time.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mike Norton ***@***.***>
Sent: Wednesday, August 17, 2022 4:04:41 PM
To: TheKrowi/Krowi_AchievementFilter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheKrowi/Krowi_AchievementFilter] Getting these 2 errors in WOTLK Beta. (Issue #19)


The addon is also not showing on the UI and seems to be blocked.

First error on load.

1x Krowi_AchievementFilter\GUI\GUI.lua:301: attempt to compare nil with number
[string ***@***.***_AchievementFilter\GUI\GUI.lua"]:301: in function <Krowi_AchievementFilter\GUI\GUI.lua:300>
[string "=[C]"]: in function `sort'
[string ***@***.***_AchievementFilter\GUI\GUI.lua"]:300: in function `TabsOrderGetActiveKeys'
[string ***@***.***_AchievementFilter\Globals.lua"]:448: in function `ChangeAchievementMicroButtonOnClick'
[string ***@***.***_AchievementFilter\Krowi_AchievementFilter-39.1.lua"]:84: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:35>

Locals:
a = <table> {
 1 = "Blizzard_AchievementUI"
 2 = "Guild"
}
b = <table> {
 1 = "Krowi_AchievementFilter"
 2 = "Achievements"
 3 = 3
}
(*temporary) = nil
(*temporary) = 3
(*temporary) = "attempt to compare nil with number"


Second bug after a moment of initial UI loading. Also happens when opening the achievement UI

1x ...ceKrowi_AchievementFilter\Data\EventData.lua:118: attempt to index global 'EventDetails' (a nil value)
[string ***@***.***_AchievementFilter\Data\EventData.lua"]:118: in function `getActiveEvents'
[string ***@***.***_AchievementFilter\GUI\Misc\AlertSystem.lua"]:33: in function <...Ons\Krowi_AchievementFilter\GUI\Misc\AlertSystem.lua:28>
[string ***@***.***_AchievementFilter\GUI\Misc\AlertSystem.lua"]:49: in function `ShowActiveWorldEvents'
[string ***@***.***_AchievementFilter\Krowi_AchievementFilter-39.1.lua"]:94: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:92>

Locals:
activeWorldEvents = <table> {
}
(*temporary) = nil
(*temporary) = false
(*temporary) = false
(*temporary) = "attempt to index global 'EventDetails' (a nil value)"
diagnostics = <table> {
 TraceEnabled = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:36
 Debug = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:9
 DebugEnabled = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:33
 Trace = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:26
 Load = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:32
 DebugTable = <function> defined @Krowi_AchievementFilter\Diagnostics.lua:15
}
GetSavedWorldEvents = <function> defined @Krowi_AchievementFilter\Data\EventData.lua:128
GetNewWorldEvents = <function> defined @Krowi_AchievementFilter\Data\EventData.lua:146

**Comment by TheKrowi** [comment]
@NoobTaco , did they add the Guild tab to the achievement window? When I ported it, it wasn't there. Can't check for myself atm.
